M48
; DRILL file KiCad 10.0.1 date 2026-08-10T00:00:42
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-10T00:00:42+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X142.185Y-77.81
X147.035Y-77.81
T2
X141.885Y-74.78
X147.335Y-74.78
M30
